# Stop at first failure (optional)
fail_fast: true

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-json
      - id: debug-statements   # optionally disallow print / pdb usage

  # isort — sort imports (compatible with black)
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black"]
        # You can add --filter-files to skip irrelevant files

  # black — code formatter
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        language_version: python3

  # flake8 — linting / style checks
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        name: flake8 (python)
        language_version: python3
        args: 
          # Exclude common directories, ignore certain codes to avoid conflicts with black
          - --exclude=venv,.venv,__pycache__,build,dist
          - --ignore=E203,W503
          - --max-line-length=88

  # mypy — type checking
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1
    hooks:
      - id: mypy
        # args: ["--ignore-missing-imports"]
