# Copy this file to config.yaml and customize for your environment

app_name: "Retail Shelf Monitoring"
debug: false

database:
  host: "localhost"
  port: 5432
  database: "retail_shelf_monitoring"
  user: "postgres"
  password: "postgres"

redis:
  host: "localhost"
  port: 6379
  db: 0
  password: null

logging:
  level: INFO
  format: json
  file_path: null

# Machine Learning Configuration
ml:
  model_path: "data/yolo11n_openvino_model/yolo11n.xml"  # Path to OpenVINO IR model
  confidence_threshold: 0.35  # Detection confidence threshold (0-1)
  nms_threshold: 0.45  # Non-maximum suppression threshold (0-1)
  device: "CPU"  # OpenVINO device (CPU, GPU, MYRIAD, etc.)

# SKU Detection Configuration
sku_detection:
  model_path: "data/mobilenet_sku.xml"  # Path to MobileNet OpenVINO model for embeddings
  index_path: "data/sku_index.faiss"  # Path to FAISS index file
  device: "CPU"  # OpenVINO device
  top_k: 1  # Number of top similar SKUs to consider

# Grid Detection Configuration
grid:
  clustering_method: "dbscan"  # Clustering method: "dbscan" or "kmeans"
  eps: 15.0  # DBSCAN epsilon parameter (distance threshold)
  min_samples: 2  # DBSCAN min_samples parameter
