# Copy this file to config.yaml and customize for your environment

app_name: "Retail Shelf Monitoring"
debug: false

database:
  host: "localhost"
  port: 5432
  database: "retail_shelf_monitoring"
  user: "postgres"
  password: "postgres"

redis:
  host: "localhost"
  port: 6379
  db: 0
  password: null

logging:
  level: INFO
  format: json
  file_path: null
